export const especialidades = [
    'Anestesiología',
    'Cardiología',
    'Coloproctología',
    'Dermatología',
    'Endocrinología',
    'Endoscopía',
    'Gastroenterología',
    'Genética Humana',
    'Ginecología Oncológica',
    'Ginecología y Obstetricia',
    'Hematología',
    'Nefrología',
    'Neumología',
    'Neurología',
    'Nutriología N. M.',
    'Odontología',
    'Oftalmología',
    'Oncología Médica',
    'Ortopedia y Traumatología',
    'Otorrinolaringología',
    'Pediatría',
    'Psicología N. M.',
    'Psiquiatría',
    'Urología'
]