export const estados = [
    {nombre:'Aguascalientes', codigo:'AS'},
    {nombre:'Baja California', codigo:'BC'},
    {nombre:'Baja California Sur', codigo:'BS'},
    {nombre:'Campeche', codigo:'CC'},
    {nombre:'Coahuila de Zaragoza', codigo:'CL'},
    {nombre:'Colima', codigo:'CM'},
    {nombre:'Chiapas', codigo:'CS'},
    {nombre:'Chihuahua', codigo:'CH'},
    {nombre:'Ciudad de México', codigo:'DF'},
    {nombre:'Durango', codigo:'DG'},
    {nombre:'Guanajuato', codigo:'GT'},
    {nombre:'Guerrero', codigo:'GR'},
    {nombre:'Hidalgo', codigo:'HG'},
    {nombre:'Jalisco', codigo:'JC'},
    {nombre:'México', codigo:'MC'},
    {nombre:'Michoacán de Ocampo', codigo:'MN'},
    {nombre:'Morelos', codigo:'MS'},
    {nombre:'Nayarit', codigo:'NT'},
    {nombre:'Nuevo León', codigo:'NL'},
    {nombre:'Oaxaca', codigo:'OC'},
    {nombre:'Puebla', codigo:'PL'},
    {nombre:'Querétaro', codigo:'QT'},
    {nombre:'Quintana Roo', codigo:'QR'},
    {nombre:'San Luis Potosí', codigo:'SP'},
    {nombre:'Sinaloa', codigo:'SL'},
    {nombre:'Sonora', codigo:'SR'},
    {nombre:'Tabasco', codigo:'TC'},
    {nombre:'Tamaulipas', codigo:'TS'},
    {nombre:'Tlaxcala', codigo:'TL'},
    {nombre:'Veracruz de Ignacio de la Llave', codigo:'VZ'},
    {nombre:'Yucátan', codigo:'YN'},
    {nombre:'Zacatecas', codigo:'ZS'},
    {nombre:'Extranjero', codigo:'NE'},
    {nombre:'Se ignora', codigo:'00'},
]